import React from 'react';
import type { Track, SocialLink } from './types';
import { InstagramIcon, FacebookIcon, YoutubeIcon } from './components/Icons';

export const BACKGROUND_IMAGES: string[] = [
  'https://images.pexels.com/photos/1169754/pexels-photo-1169754.jpeg', // Nebula
  'https://images.pexels.com/photos/2150/sky-space-dark-galaxy.jpg', // Galaxy
  'https://images.pexels.com/photos/1252890/pexels-photo-1252890.jpeg', // Pink & Blue Nebula
  'https://images.pexels.com/photos/956999/milky-way-starry-sky-night-sky-star-956999.jpeg', // Milky Way
  'https://images.pexels.com/photos/1274260/pexels-photo-1274260.jpeg', // Stars and horizon
  'https://images.pexels.com/photos/39561/solar-flare-sun-eruption-energy-39561.jpeg', // Solar Flare
];

// NOTE: The full track is now fetched from a secure, temporary link
// generated by the backend after a successful purchase.
// 'priceId' is no longer used, but kept for potential future integrations.

export const TRACKS: Track[] = [
  {
    id: 'cosmosonic-01',
    title: 'Orion',
    artist: 'Julio César THOR',
    coverArt: 'https://pub-1e5d25b634314db58b1875cea93e83a7.r2.dev/cosmosonic-01.png',
    audioSrc: 'https://pub-1e5d25b634314db58b1875cea93e83a7.r2.dev/1_Orion.mp3',
    price: 0.01, // Price lowered for testing
    priceId: 'coinbase-charge', 
    fileName: '1_Orion.mp3',
  },
  {
    id: 'cosmosonic-02',
    title: 'Moon',
    artist: 'Julio César THOR',
    coverArt: 'https://pub-1e5d25b634314db58b1875cea93e83a7.r2.dev/cosmosonic-02.png',
    audioSrc: 'https://pub-1e5d25b634314db58b1875cea93e83a7.r2.dev/2_Moon.mp3',
    price: 0.99,
    priceId: 'coinbase-charge',
    fileName: '2_Moon.mp3',
  },
  {
    id: 'cosmosonic-03',
    title: 'Earth',
    artist: 'Julio César THOR',
    coverArt: 'https://pub-1e5d25b634314db58b1875cea93e83a7.r2.dev/cosmosonic-03.png',
    audioSrc: 'https://pub-1e5d25b634314db58b1875cea93e83a7.r2.dev/3_Earth.mp3',
    price: 0.99,
    priceId: 'coinbase-charge',
    fileName: '3_Earth.mp3',
  },
  {
    id: 'cosmosonic-04',
    title: 'Orion II',
    artist: 'Julio César THOR',
    coverArt: 'https://pub-1e5d25b634314db58b1875cea93e83a7.r2.dev/cosmosonic-04.png',
    audioSrc: 'https://pub-1e5d25b634314db58b1875cea93e83a7.r2.dev/4_Orion_II.mp3',
    price: 0.99,
    priceId: 'coinbase-charge',
    fileName: '4_Orion_II.mp3',
  },
];

export const SOCIAL_LINKS: SocialLink[] = [
  { name: 'Instagram', url: 'https://www.instagram.com/juliocesarthor', icon: <InstagramIcon /> },
  { name: 'Facebook', url: 'https://www.facebook.com/juliocesarthor/', icon: <FacebookIcon /> },
  { name: 'YouTube', url: 'https://www.youtube.com/@juliocesarthor3785', icon: <YoutubeIcon /> },
];
