import React from 'react';
import type { Track, SocialLink } from './types';
import { SpotifyIcon, InstagramIcon, XIcon, YoutubeIcon } from './components/Icons';

// NOTE: The full track is now fetched from a secure, temporary link
// generated by the backend after a successful purchase.
// 'priceId' is no longer used, but kept for potential future integrations.

export const TRACKS: Track[] = [
  {
    id: 'cosmosonic-01',
    title: 'Orion',
    artist: 'Julio César THOR',
    coverArt: 'https://pub-1e5d25b634314db58b1875cea93e83a7.r2.dev/cosmosonic-01.png',
    price: 0.01, // Price lowered for testing
    priceId: 'coinbase-charge', 
  },
  {
    id: 'cosmosonic-02',
    title: 'Moon',
    artist: 'Julio César THOR',
    coverArt: 'https://pub-1e5d25b634314db58b1875cea93e83a7.r2.dev/cosmosonic-02.png',
    price: 0.99,
    priceId: 'coinbase-charge',
  },
  {
    id: 'cosmosonic-03',
    title: 'Earth',
    artist: 'Julio César THOR',
    coverArt: 'https://pub-1e5d25b634314db58b1875cea93e83a7.r2.dev/cosmosonic-03.png',
    price: 0.99,
    priceId: 'coinbase-charge',
  },
  {
    id: 'cosmosonic-04',
    title: 'Orion p.2',
    artist: 'Julio César THOR',
    coverArt: 'https://pub-1e5d25b634314db58b1875cea93e83a7.r2.dev/cosmosonic-04.png',
    price: 0.99,
    priceId: 'coinbase-charge',
  },
];

export const SOCIAL_LINKS: SocialLink[] = [
  { name: 'Spotify', url: '#', icon: <SpotifyIcon /> },
  { name: 'Instagram', url: '#', icon: <InstagramIcon /> },
  { name: 'X', url: '#', icon: <XIcon /> },
  { name: 'YouTube', url: '#', icon: <YoutubeIcon /> },
];
